import axios from 'axios';
import dotenv from 'dotenv';

dotenv.config();

const APIFY_TOKEN = process.env.APIFY_TOKEN;
const ACTOR_ID = 'streamers~youtube-scraper';

export const getChannelInfo = async (channelUrl: string): Promise<{ id: string, name: string, thumbnail: string, subscribers: number } | null> => {
    if (!APIFY_TOKEN) return null;
    try {
        console.log(`Fetching channel info via Apify for: ${channelUrl}`);
        const runResponse = await axios.post(`https://api.apify.com/v2/acts/${ACTOR_ID}/runs?token=${APIFY_TOKEN}`, {
            startUrls: [{ url: channelUrl }],
            maxResultDeserializationLimit: 1
        });
        const runId = runResponse.data.data.id;
        const defaultDatasetId = runResponse.data.data.defaultDatasetId;
        console.log(`Apify Channel Info Run ID: ${runId}`);

        // Simple poll
        let finished = false;
        while (!finished) {
            const statusRes = await axios.get(`https://api.apify.com/v2/actor-runs/${runId}?token=${APIFY_TOKEN}`);
            const status = statusRes.data.data.status;
            console.log(`Apify Run Status: ${status}`);
            if (status === 'SUCCEEDED') finished = true;
            else if (['FAILED', 'ABORTED', 'TIMED-OUT'].includes(status)) return null;
            else await new Promise(r => setTimeout(r, 3000));
        }

        const res = await axios.get(`https://api.apify.com/v2/datasets/${defaultDatasetId}/items?token=${APIFY_TOKEN}`);
        console.log(`Apify Dataset Items Count: ${res.data.length}`);
        const item = res.data[0];
        if (item) {
            console.log("Raw Apify Item [0]:", JSON.stringify(item, null, 2));
            return {
                id: item.channelId || item.id,
                name: item.channelName || item.title,
                thumbnail: item.channelAvatarUrl || item.channelThumbnail || item.thumbnailUrl,
                subscribers: item.numberOfSubscribers || 0
            };
        }
    } catch (e) {
        console.error("Apify channel info error:", e);
    }
    return null;
};

export const getLatestVideos = async (channelUrl: string, limit: number = 5, publishedAfter?: string): Promise<any[]> => {
    if (!APIFY_TOKEN) return [];
    try {
        console.log(`Fetching latest videos via Apify for: ${channelUrl} (after: ${publishedAfter || 'all time'})`);

        const payload: any = {
            startUrls: [{ url: channelUrl }],
            maxResults: limit,
        };

        if (publishedAfter) {
            payload.publishedAfter = publishedAfter;
        }

        const runResponse = await axios.post(`https://api.apify.com/v2/acts/${ACTOR_ID}/runs?token=${APIFY_TOKEN}`, payload);
        const runId = runResponse.data.data.id;
        const defaultDatasetId = runResponse.data.data.defaultDatasetId;

        let finished = false;
        while (!finished) {
            const statusRes = await axios.get(`https://api.apify.com/v2/actor-runs/${runId}?token=${APIFY_TOKEN}`);
            if (statusRes.data.data.status === 'SUCCEEDED') finished = true;
            else if (['FAILED', 'ABORTED', 'TIMED-OUT'].includes(statusRes.data.data.status)) return [];
            else await new Promise(r => setTimeout(r, 5000));
        }

        const res = await axios.get(`https://api.apify.com/v2/datasets/${defaultDatasetId}/items?token=${APIFY_TOKEN}`);
        return res.data.map((v: any) => ({
            id: v.id || v.videoId,
            title: v.title,
            description: v.description,
            publishedAt: v.date || v.publishedAt,
            thumbnail: v.thumbnailUrl || v.thumbnail
        }));
    } catch (e) {
        console.error("Apify latest videos error:", e);
    }
    return [];
};

export const getTranscript = async (videoUrl: string): Promise<string | null> => {
    if (!APIFY_TOKEN) {
        console.error('APIFY_TOKEN is not set');
        return null;
    }

    try {
        console.log(`Starting Apify YouTube Scraper for: ${videoUrl}`);

        // Start the actor
        const runResponse = await axios.post(
            `https://api.apify.com/v2/acts/${ACTOR_ID}/runs?token=${APIFY_TOKEN}`,
            {
                startUrls: [{ url: videoUrl }],
                downloadSubtitles: true,
                subtitleLanguage: 'Any',
                subtitleFormat: 'plaintext',
                preferAutoGeneratedSubtitles: false,
                maxResultDeserializationLimit: 1
            }
        );

        const runId = runResponse.data.data.id;
        const defaultDatasetId = runResponse.data.data.defaultDatasetId;

        console.log(`Apify run started: ${runId}. Waiting for completion...`);

        // Poll for completion
        let finished = false;
        let attempts = 0;
        while (!finished && attempts < 30) {
            await new Promise(resolve => setTimeout(resolve, 5000));
            const statusResponse = await axios.get(
                `https://api.apify.com/v2/actor-runs/${runId}?token=${APIFY_TOKEN}`
            );
            const status = statusResponse.data.data.status;
            if (status === 'SUCCEEDED') {
                finished = true;
            } else if (status === 'FAILED' || status === 'ABORTED' || status === 'TIMED-OUT') {
                throw new Error(`Apify run ${status}`);
            }
            attempts++;
        }

        if (!finished) throw new Error('Apify run timed out');

        // Get the results from dataset
        const datasetResponse = await axios.get(
            `https://api.apify.com/v2/datasets/${defaultDatasetId}/items?token=${APIFY_TOKEN}`
        );

        const items = datasetResponse.data;
        if (items && items.length > 0) {
            const videoData = items[0];
            // The YouTube scraper returns subtitles in a generic format if requested
            if (videoData.subtitles && Array.isArray(videoData.subtitles)) {
                // If it's a structural array of subtitles, flatten them out. If plaintext was successful, it might just be string.
                if (typeof videoData.subtitles[0] === 'string') {
                    return videoData.subtitles.join('\n');
                } else if (videoData.subtitles[0].text) {
                    return videoData.subtitles.map((s: any) => s.text).join('\n');
                } else {
                    return JSON.stringify(videoData.subtitles);
                }
            } else if (typeof videoData.subtitles === 'string') {
                return videoData.subtitles;
            }
            // fallback
            return videoData.description || videoData.title || null;
        }

        return null;
    } catch (error) {
        console.error('Error fetching transcript from Apify:', error);
        return null;
    }
};
